config = {
        "audio_dir": "./vctk/VCTK-Corpus/wav48/p225",
        "model_dir": "/data2/wl/wavenet/ckpts",
        "wandb_project_name": "wavenet-audio-generation",
        "sample_rate": 16000, 
        "quantization_channels": 256,
        "segment_length": 8000, 
        "max_dataset_samples": 1000,
        "wavenet_layer_size": 10,
        "wavenet_stack_size": 4,
        "wavenet_res_channels": 256,
        "wavenet_skip_channels": 256,
        "batch_size": 4,
        "epochs": 50,
        "learning_rate": 1e-4, 
        "num_workers": 8, 
        "log_interval": 5, 
        "save_interval": 5, 
        "generation_interval": 5, 
        "generation_length": 16000 * 2, 
        "generation_temperature": 0.8,
    }